# Spring properties
spring:
  application:
     name: shop-ms

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-sample-registry:8761/eureka/

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port


spring:
  mail:
    host: 11.133.129.10
    username: aymen.jaaouane@yahoo.fr

message: HELLO AYMEN

